### ISSUE TITLE
How to Run each tag?

### ISSUE THREAD

**Issue by gayanscorpio** [spapas/react-tutorial#2]
```
react-only
react-only-validation
react-flux
react-flux-better-organization
react-flux-complex
```

please be kind enough to give commands , how to run in each tag?

i tried , npm install , and npm start , but it does not work....

**Comment by spapas** [comment]
Hello @gayanscorpio - I don't use npm start since this project is based on python/django as a server-side framework. I've already updated the README with instructions so please look there (hint: try running `python manage.py runserver`)
