### ISSUE TITLE
react-redux tag

### ISSUE THREAD

**Issue by FerreiraRaphael** [spapas/react-tutorial#3]
I'am following the http://spapas.github.io/2016/03/02/react-redux-tutorial/ article and i see that the tag react-redux isn't available, why ?

**Comment by spapas** [comment]
Hello @FerreiraRaphael thanks for noticing! The react-redux tag should have been the current version of the code but I had forgotten to tag it. I've added it now for completeness.

**Comment by FerreiraRaphael** [comment]
thank you @spapas, for the tutorial :)
