### ISSUE TITLE
__init__.py missing from books

### ISSUE THREAD

**Issue by jusic** [spapas/react-tutorial#5]
Hi,

Thanks for the tutorial.

It looks like `__init__.py` file is missing from `books`, which blocks `python manage.py syncdb` or `migrate`.

**Comment by spapas** [comment]
Hello @jusic thanks for this. 

It seems that the **init**.py was accidentally deleted (from what I saw, there actually was an **init**.pyc in my local repo so everything worked there). In any case, I've added it and everything should work fine now.
