### ISSUE TITLE
how do get categories working?

### ISSUE THREAD

**Issue by flacoman91** [spapas/react-tutorial#8]
Hello, I am trying to run the complex examples with categories and the cascading drop downs and they don't appear to be working for me.  The dropdowns are empty for both categories and subcategories

the categories work on simple examples though. 

I do a fresh install and delete the sqlite file, and run the migrate command each time i switch tags.

Any suggestions are much appreciated. thanks!

**Comment by spapas** [comment]
Hello @flacoman91, this is really strange. Have you added categories and subcategories through the django-admin? Here's what I did right now (and everything worked ok):

I use the latest version from master (I have activated a virtualenv first):
```
git fetch origin
git merge origin/master
```

then I install all deps for python and js
```
npm install
pip install -r requirements.txt
``` 

then create a new database and a superuser
```
del db.sqlite3
python manage.py migrate
python manage.py createsuperuser
```

Then run the python dev server
```
python manage.py runserver
```
and from a different command line I run
```
npm run watch
```
to start watchify so it compiles my JS assets.

Now I visit http://127.0.0.1:8000/admin, login with my superuser credentials and add a bunch of categories and subcategories. Maybe you forgot to do that? From what I see, the initial-simpler versions (for example react-only) were using hard-coded categories (https://github.com/spapas/react-tutorial/blob/react-only/books/models.py) so you didn't need to visit the django-admin to add them yourself.

Finally, I can go to http://127.0.0.1:8000/ and everything is working fine. Can you try it again? Do you see any errors in your javascript console or in command line?

**Comment by flacoman91** [comment]
So sorry about that.  I'm just learning react and have never used django.  
I didn't know I had to create a user and populate the data manually.
That was the steps that I was missing.

Awesome tutorial and thank you very much for sharing this!

**Comment by spapas** [comment]
No problem I should have mentioned that in the readme. I totally recommend django, in my opinion it's the best server side framework today.
